/**
 * .invoice — real PDF invoices 💼
 *
 *   .invoice new "Web Design" 45000 "Jane Doe"      → creates + sends invoice PDF
 *   .invoice list                                     → your invoices
 *   .invoice paid 1                                   → mark #1 paid
 *   .invoice stats                                    → totals: outstanding vs paid
 *
 * Persisted; PDFkit renders a clean branded invoice.
 */
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const settingsStore = require('../utils/settingsStore');
const config = require('../config/config');
const tk = require('../utils/timekeeper');
const { isOwner } = require('../utils/isOwner');

const KEY = 'invoices';
const DIR = path.join(__dirname, '../vault/invoices');

function load() { return settingsStore.get(KEY, []); }
function save(v) { settingsStore.set(KEY, v); }
function nextNo() { return 'INV-' + new Date().getFullYear() + '-' + String(load().length + 1).padStart(3, '0'); }

async function buildPDF(inv) {
  if (!fs.existsSync(DIR)) fs.mkdirSync(DIR, { recursive: true });
  const file = path.join(DIR, `${inv.no}.pdf`);
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(file);
    doc.pipe(stream);

    // header
    doc.fontSize(26).fillColor('#7a52ff').text('CELESTIA', 50, 50);
    doc.fontSize(9).fillColor('#666').text('INVOICE — professional services', 50, 82);
    doc.moveTo(50, 100).lineTo(545, 100).lineWidth(1).strokeColor('#00e5ff').stroke();

    // meta
    doc.fontSize(10).fillColor('#333');
    doc.text(`Invoice: ${inv.no}`, 350, 55, { width: 174, align: 'right' });
    doc.text(`Date: ${new Date(inv.date).toLocaleDateString()}`, 350, 72, { width: 174, align: 'right' });
    doc.text(`Status: ${inv.paid ? 'PAID' : 'DUE'}`, 350, 89, { width: 174, align: 'right', color: inv.paid ? '#0a0' : '#d33' });

    // parties
    doc.fontSize(9).fillColor('#666').text('FROM', 50, 120);
    doc.fontSize(11).fillColor('#111').text('Your Business', 50, 136);
    doc.fontSize(9).fillColor('#666').text('TO', 350, 120);
    doc.fontSize(11).fillColor('#111').text(inv.client, 350, 136, { width: 174 });

    // items
    let y = 180;
    doc.fontSize(10).fillColor('#666').text('DESCRIPTION', 50, y);
    doc.text('AMOUNT', 450, y, { width: 74, align: 'right' });
    y += 8;
    doc.moveTo(50, y).lineTo(545, y).stroke('#ccc');
    y += 18;
    doc.fontSize(12).fillColor('#111').text(inv.description, 50, y, { width: 380 });
    doc.text(inv.currency + ' ' + inv.amount.toLocaleString(), 450, y, { width: 74, align: 'right' });
    y += 60;
    doc.moveTo(50, y).lineTo(545, y).stroke('#ccc');
    y += 12;
    doc.fontSize(14).fillColor('#111').text('TOTAL', 450, y, { width: 74, align: 'right' });
    doc.fontSize(16).fillColor('#7a52ff').text(inv.currency + ' ' + inv.amount.toLocaleString(), 380, y + 20, { width: 144, align: 'right' });

    doc.fontSize(8).fillColor('#999').text('Generated by CELESTIA — the most beautiful bot', 50, 730, { width: 495, align: 'center' });

    doc.end();
    stream.on('finish', () => resolve({ file, buffer: fs.readFileSync(file) }));
    stream.on('error', reject);
  });
}

module.exports = {
  name: 'invoice',
  aliases: ['inv'],
  description: '💼 Real PDF invoices — .invoice new "<description>" <amount> "<client>"',
  async execute(sock, msg, args, commands, reply) {
    if (!isOwner(msg)) return reply('💼 _The ledger belongs to one._');
    const sub = (args[0] || '').toLowerCase();
    const jid = msg.key.remoteJidAlt || msg.key.remoteJid;

    // ─── new ───
    if (sub === 'new' || sub === 'create') {
      // format: .invoice new "desc" amount "client"
      const line = args.slice(1).join(' ');
      const m = line.match(/"([^"]+)"\s+(\d+(?:\.\d+)?)\s+"([^"]+)"/);
      if (!m) {
        return reply('💼 Format: *.invoice new "Web Design" 45000 "Jane Doe"*\n_amount in your currency_');
      }
      const [, description, amountStr, client] = m;
      const amount = parseFloat(amountStr);
      const inv = {
        no: nextNo(),
        description,
        amount,
        client,
        currency: 'KES',
        date: Date.now(),
        paid: false,
      };
      const list = load();
      list.push(inv);
      save(list);
      const { buffer, file } = await buildPDF(inv);
      await sock.sendMessage(jid, {
        document: buffer,
        mimetype: 'application/pdf',
        fileName: `${inv.no}.pdf`,
        caption: `💼 *${inv.no}*\n${description} — ${inv.currency} ${amount.toLocaleString()}\nTo: ${client}\n\n_Mark paid: \`.invoice paid ${list.length}\`_`,
      }, { quoted: msg });
      return;
    }

    // ─── paid ───
    if (sub === 'paid') {
      const list = load();
      const i = parseInt(args[1], 10) - 1;
      if (isNaN(i) || i < 0 || i >= list.length) return reply('💼 `.invoice paid 1` — number from `.invoice list`');
      list[i].paid = true;
      list[i].paidAt = Date.now();
      save(list);
      return reply(`💼 *${list[i].no}* marked PAID. 💰`);
    }

    // ─── stats ───
    if (sub === 'stats' || sub === 'total') {
      const list = load();
      if (!list.length) return reply('💼 No invoices yet. `.invoice new "Work" 5000 "Client"`');
      const paid = list.filter(i => i.paid);
      const due = list.filter(i => !i.paid);
      const sum = (arr) => arr.reduce((s, i) => s + i.amount, 0);
      return reply(
        `💼 *LEDGER*\n\n` +
        `🧾 Total invoices: ${list.length}\n` +
        `💰 Paid: ${sum(paid).toLocaleString()} (${paid.length})\n` +
        `⏳ Outstanding: *${sum(due).toLocaleString()}* (${due.length})\n\n` +
        `_Chase gently. The stars favor the bold invoice._`
      );
    }

    // ─── list ───
    const list = load();
    if (!list.length) {
      return reply('💼 No invoices yet.\n\n*.invoice new "Web Design" 45000 "Jane Doe"*');
    }
    const L = ['💼 *YOUR INVOICES*', ''];
    list.forEach((i, idx) => {
      L.push(`${idx + 1}. ${i.paid ? '✅' : '⏳'} *${i.no}* — ${i.currency} ${i.amount.toLocaleString()}`);
      L.push(`   "${i.description.slice(0, 30)}" → ${i.client}`);
    });
    L.push('', '_`.invoice paid <n>` • `.invoice stats`_');
    return reply(L.join('\n'));
  },
};
