const { isSudo } = require('../utils/isSudo');
const { fetchPairingCode } = require('../utils/pairCode');
module.exports = {
  name: 'pair',
  aliases: ['rent'],
  description: 'Get a WhatsApp pairing code for a number (owner/sudo only)',
  async execute(sock, msg, args) {
    const jid = msg.key.remoteJid;
    if (!isSudo(msg)) {
      return;
    }
    const q = args.join(' ').trim();
    if (!q) {
      return await sock.sendMessage(
        jid,
        { text: 'Please provide a valid WhatsApp number.\n\nExample: .pair 254754574XXX' },
        { quoted: msg }
      );
    }
    const numbers = q
      .split(',')
      .map((v) => v.replace(/[^0-9]/g, ''))
      .filter((v) => v.length > 5 && v.length < 20);
    if (numbers.length === 0) {
      return await sock.sendMessage(
        jid,
        { text: '❌ Invalid number. Please use the correct format.' },
        { quoted: msg }
      );
    }
    for (const number of numbers) {
      // Overlap the ack send with the code request instead of awaiting
      // three serial round trips — this is where the old delay came from.
      const requestingP = sock.sendMessage(
        jid,
        { text: `⏳ Requesting pairing code for ${number}...` },
        { quoted: msg }
      );
      let code;
      try {
        // LOCAL ONLY: code is generated by our own linked socket.
        // Never routed through any external pairing service.
        code = await fetchPairingCode(sock, number);
      } catch (error) {
        console.error('[PAIR ERROR]', error.message);
        const done = await requestingP.catch(() => null);
        const failedText = error.code === 'NOT_REGISTERED'
          ? `❗ ${number} is not registered on WhatsApp.`
          : /timed out/.test(error.message)
            ? `⚠️ WhatsApp took too long for ${number} — network is slow right now. Try again in a bit.`
            : `⚠️ Failed to get pairing code for ${number}.`;
        if (done) {
          await sock.sendMessage(jid, { text: failedText, edit: done.key }).catch(() => sock.sendMessage(jid, { text: failedText }, { quoted: msg }));
        } else {
          await sock.sendMessage(jid, { text: failedText }, { quoted: msg });
        }
        continue;
      }
      const requestingMsg = await requestingP;
        // Code goes in its own message, alone, wrapped in backticks —
        // a tap/long-press then selects exactly the code, nothing else.
        await sock.sendMessage(jid, { text: `\`${code}\`` });
        // Edit the original "Requesting..." message in place instead of
        // sending a third message — keeps the chat cleaner.
        await sock.sendMessage(
          jid,
          {
            text: `🔗 Pairing code for ${number} below — tap and hold to copy.`,
            edit: requestingMsg.key,
          }
        );
    }
  },
};
