const { isSudo } = require('../utils/isSudo');
const { fetchPairingCode } = require('../utils/pairCode');

module.exports = {
  name: 'pair2',
  aliases: ['rent2'],
  description: 'Get a WhatsApp pairing code (local socket, owner/sudo only)',

  async execute(sock, msg, args) {
    const jid = msg.key.remoteJid;

    if (!isSudo(msg)) {
      return;
    }

    const q = args.join(' ').trim();

    if (!q) {
      return await sock.sendMessage(
        jid,
        {
          text: 'Please provide a valid WhatsApp number.\n\nExample: .pair2 254754574XXX'
        },
        { quoted: msg }
      );
    }

    const numbers = q
      .split(',')
      .map((v) => v.replace(/[^0-9]/g, ''))
      .filter((v) => v.length > 5 && v.length < 20);

    if (numbers.length === 0) {
      return await sock.sendMessage(
        jid,
        { text: '❌ Invalid number. Please use the correct format.' },
        { quoted: msg }
      );
    }

    for (const number of numbers) {
      // Overlap the ack send with the code request — same fast path as .pair.
      const requestingP = sock.sendMessage(
        jid,
        {
          text: `⏳ Requesting pairing code for ${number}...`
        },
        { quoted: msg }
      );
      let code;
      try {
        // LOCAL ONLY: identical to .pair — generated by our own socket.
        code = await fetchPairingCode(sock, number);
      } catch (error) {
        console.error('[PAIR2 ERROR]', error.message);
        const done = await requestingP.catch(() => null);
        const failedText = error.code === 'NOT_REGISTERED'
          ? `❗ ${number} is not registered on WhatsApp.`
          : /timed out/.test(error.message)
            ? `⚠️ WhatsApp took too long for ${number} — network is slow right now. Try again in a bit.`
            : `⚠️ Failed to get pairing code for ${number}.`;
        if (done) {
          await sock.sendMessage(jid, { text: failedText, edit: done.key }).catch(() => sock.sendMessage(jid, { text: failedText }, { quoted: msg }));
        } else {
          await sock.sendMessage(jid, { text: failedText }, { quoted: msg });
        }
        continue;
      }
      const requestingMsg = await requestingP;

        await sock.sendMessage(jid, {
          text: `\`${code}\``
        });

        await sock.sendMessage(
          jid,
          {
            text: `🔗 Pairing code for ${number} below — tap and hold to copy.`,
            edit: requestingMsg.key
          }
        );
    }
  }
};
